bt_garage_navigator:
  ros__parameters:
    use_sim: false
    default_nav_garage_avoidance_bt_xml: /workspaces/capella_ros_docker/install/share/garage_navigator/behavior_trees/garage2.xml
    plugin_lib_names:
      - "compute_right_edge_path_action"
      - "find_car_avoidance_point_action"
      - "nav2_pipeline_sequence_bt_node"
      - "nav2_recovery_node_bt_node"
      - "nav2_rate_controller_bt_node"
      - "nav2_compute_path_through_poses_action_bt_node"
      - "nav2_compute_path_to_pose_action_bt_node"
      - "nav2_round_robin_node_bt_node"
      - "nav2_clear_costmap_service_bt_node"
      - "nav2_follow_path_action_bt_node"
      - "nav2_goal_updated_condition_bt_node"
      - nav2_goal_updater_node_bt_node
      - "nav2_wait_action_bt_node"
      - "welt_model_node"
      - "nav2_single_trigger_bt_node"
      - "nav2_remove_passed_goals_action_bt_node"
      - nav2_goal_updated_controller_bt_node

      # - nav2_compute_path_to_pose_action_bt_node
      # - nav2_compute_path_through_poses_action_bt_node
      # - nav2_smooth_path_action_bt_node
      # - nav2_follow_path_action_bt_node
      # - nav2_spin_action_bt_node
      # - nav2_wait_action_bt_node
      # - nav2_assisted_teleop_action_bt_node
      # - nav2_back_up_action_bt_node
      # - nav2_drive_on_heading_bt_node
      # - nav2_clear_costmap_service_bt_node
      # - nav2_is_stuck_condition_bt_node
      # - nav2_goal_reached_condition_bt_node
      # - nav2_goal_updated_condition_bt_node
      # - nav2_globally_updated_goal_condition_bt_node
      # - nav2_is_path_valid_condition_bt_node
      # - nav2_initial_pose_received_condition_bt_node
      # - nav2_reinitialize_global_localization_service_bt_node
      # - nav2_rate_controller_bt_node
      # - nav2_distance_controller_bt_node
      # - nav2_speed_controller_bt_node
      # - nav2_truncate_path_action_bt_node
      # - nav2_truncate_path_local_action_bt_node
      # - nav2_goal_updater_node_bt_node
      # - nav2_recovery_node_bt_node
      # - nav2_pipeline_sequence_bt_node
      # - nav2_round_robin_node_bt_node
      # - nav2_transform_available_condition_bt_node
      # - nav2_time_expired_condition_bt_node
      # - nav2_path_expiring_timer_condition
      # - nav2_distance_traveled_condition_bt_node
      # - nav2_single_trigger_bt_node
      # - nav2_goal_updated_controller_bt_node
      # - nav2_is_battery_low_condition_bt_node
      # - nav2_navigate_through_poses_action_bt_node
      # - nav2_navigate_to_pose_action_bt_node
      # - nav2_remove_passed_goals_action_bt_node
      # - nav2_planner_selector_bt_node
      # - nav2_controller_selector_bt_node
      # - nav2_goal_checker_selector_bt_node
      # - nav2_controller_cancel_bt_node
      # - nav2_path_longer_on_approach_bt_node
      # - nav2_wait_cancel_bt_node
      # - nav2_spin_cancel_bt_node
      # - nav2_back_up_cancel_bt_node
      # - nav2_assisted_teleop_cancel_bt_node
      # - nav2_drive_on_heading_cancel_bt_node

lifecycle_manager:
  ros__parameters:
    autostart: true
    node_names:
      [
        "bt_garage_navigator",
        "robot_avoidance"
      ]
    bond_timeout: 4.0

test_garage_action_client:
  ros__parameters:
    test_cancel: false
    test_in_garage: true
    polygons:
      # - "[[4.5, -6.0],[4.0, 0.0],[2.0, 0.0],[2.5, -6.0]]"           # 一楼3通道 begin
      # - "[[4.5, -6.0],[4.5, -8.0],[-6.0, -8.0],[-6.0, -6.0]]"
      # - "[[2.0, 0.0],[-5.0, 0.0],[-5.0, -2.0],[2.0, -2.0]]"         # 一楼3通道 end
      - "[[-8.7, 9.3], [-6.5, 11.5], [18.5, -16.0], [16.2,-18.1]]"  # -1楼3米通道
      # - "[[-10.2, 9.5], [-6.5, 11.5], [18.5, -16.0], [14.7,-19.3]]" # -1楼4米通道
      # - "[[-10.2, 9.5], [-6.5, 11.5], [18.5, -16.0], [14.7,-19.3]]" # -1楼6米通道

