

car_costmap:
  car_costmap:
    ros__parameters:
      update_frequency: 2.0 #原始值为1.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
        # robot_radius: 0.55 #用于设置要使用的机器人半径
      footprint: "[[-0.406, -0.465], [-0.406, 0.465], [0.406, 0.465], [0.406, -0.465]]"
      resolution: 0.05 #用于设置成本地图上1个像素的分辨率，单位为m
      track_unknown_space: true  #用于设置是否将未知空间视为空闲空间。如果为false，则会将未知空间视为空闲空间；否则视为未知空间
      plugins: ["static_layer", "voxel_layer", "keepout_filter", "inflation_layer"]
      filters: ["keepout_filter"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan  #point2scan_front_up point2scan_front_down  #point2scan_back #person_cloud
        scan:
          topic: /scan
          obstacle_max_range: 10.0
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
        point2scan_back:
          topic: /point_scan_back
          max_obstacle_height: 3.0
          obstacle_max_range: 3.0
          min_obstacle_height: 0.0
          expected_update_rate: 0.7
          clearing: True
          marking: True
          data_type: "LaserScan"
        point2scan_front_up:
          topic: /point_scan_front_up
          max_obstacle_height: 1.8
          min_obstacle_height: 0.0
          obstacle_max_range: 3.0
          expected_update_rate: 0.7
          clearing: True
          marking: True
          data_type: "LaserScan"
        point2scan_front_down:
          topic: /point_scan_front_down
          max_obstacle_height: 3.0
          obstacle_max_range: 3.0
          min_obstacle_height: 0.0
          expected_update_rate: 0.7
          clearing: True
          marking: True
          data_type: "LaserScan"
        person_cloud:
          topic: /points_cloud_person
          max_obstacle_height: 3.0
          obstacle_max_range: 3.0
          min_obstacle_height: 0.0
          expected_update_rate: 0.7
          clearing: True
          marking: True
          data_type: "PointCloud2"
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        combination_method:       1
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          obstacle_max_range: 4.0
          obstacle_min_range: 0.05
          inf_is_valid: true
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/nav/keepout/info"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.8  #扩大致命障碍物周围的成本图的半径
      always_send_full_costmap: True

  car_costmap_client:
    ros__parameters:
      use_sim_time: False

  car_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

robot_avoidance_node:
  ros__parameters:
    safe_width_threshold: 0.2
    start_end_path_threshold: 2.0
    car_size_threshold: 1.0

welt_model_node:
  ros__parameters:
    footprint_w: 0.2
    footprint_h_back: 0.2
    footprint_h_front: 0.2